### ISSUE TITLE
What's the dedicate environment of this repo?

### ISSUE THREAD

**Issue by hunterMG** [ma7555/nnDPI#1]
eg. python version, TF version, dependency python packages...?
That would be very nice of you if you add a **.env** file for it or add some instructions in **README.md**?
There will be more convenient for others to contribute to your work if you do that.

**Comment by ma7555** [comment]
@hunterMG,
This was trained on Python v3.7.9 and TF v2.1 but I believe it will work on all TFv2.x
I will add a yml conda enviroment file later on. Thanks for the suggestion
